export const DEMO_BUSINESS_LIST = [
  "Golf",
  "Badmintons",
  "Shirts",
  "Pants",
  "Basketballs",
  "Sneakers",
  "Bicycles"
];

export const DEMO_PRODUCT_LIST = [
  {
    prod_id: 'P0PJ001',
    prod_name: 'Golf Club Set',
    prod_description: 'Complete set of golf clubs for all skill levels.',
    prod_stockqty: 15,
    prod_price: 499.99,
    prod_modelnum: 'GC-001',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Not Available',
  },
  {
    prod_id: 'P0PJ002',
    prod_name: 'Golf Ball Pack',
    prod_description: 'High-quality golf balls for maximum distance and accuracy.',
    prod_stockqty: 50,
    prod_price: 29.99,
    prod_modelnum: 'GB-002',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ003',
    prod_name: 'Golf Glove',
    prod_description: 'Premium leather golf glove for a comfortable grip.',
    prod_stockqty: 30,
    prod_price: 19.99,
    prod_modelnum: 'GG-003',
    cat_id: 'Golf',
    sub_cat: 'Apparel',
    prod_status: 'Not Available',
  },
  {
    prod_id: 'P0PJ004',
    prod_name: 'Golf Cart Bag',
    prod_description: 'Lightweight and durable cart bag for your golf clubs.',
    prod_stockqty: 20,
    prod_price: 129.99,
    prod_modelnum: 'GB-004',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ005',
    prod_name: 'Golf Polo Shirt',
    prod_description: 'Stylish polo shirt designed for golfers.',
    prod_stockqty: 40,
    prod_price: 39.99,
    prod_modelnum: 'GPS-005',
    cat_id: 'Golf',
    sub_cat: 'Apparel',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ006',
    prod_name: 'Golf Umbrella',
    prod_description: 'Large golf umbrella for sun and rain protection on the course.',
    prod_stockqty: 25,
    prod_price: 24.99,
    prod_modelnum: 'GU-006',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ007',
    prod_name: 'Golf Driver',
    prod_description: 'High-performance golf driver for long drives.',
    prod_stockqty: 10,
    prod_price: 249.99,
    prod_modelnum: 'GD-007',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ008',
    prod_name: 'Golf Shoes',
    prod_description: 'Comfortable and spikeless golf shoes for better traction.',
    prod_stockqty: 35,
    prod_price: 79.99,
    prod_modelnum: 'GS-008',
    cat_id: 'Golf',
    sub_cat: 'Footwear',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ009',
    prod_name: 'Golf Putting Mat',
    prod_description: 'Practice your putting skills at home with this mat.',
    prod_stockqty: 15,
    prod_price: 49.99,
    prod_modelnum: 'GPM-009',
    cat_id: 'Golf',
    sub_cat: 'Equipment',
    prod_status: 'Available',
  },
  {
    prod_id: 'P0PJ010',
    prod_name: 'Golf Sun Visor',
    prod_description: 'Visor hat with UV protection for sunny days on the golf course.',
    prod_stockqty: 30,
    prod_price: 14.99,
    prod_modelnum: 'GSV-010',
    cat_id: 'Golf',
    sub_cat: 'Apparel',
    prod_status: 'Available',
  },
];

export const DEMO_CUSTOMER_LIST = [
  {
    user_id: 'CUST0001',
    user_name: 'Aneh neh',
    last_login_date: '2023-09-01',
    last_login_time: '13:45:30',
    status: 'Approved',
  },
  {
    user_id: 'CUST0002',
    user_name: 'Bhenchod',
    last_login_date: '2023-09-02',
    last_login_time: '13:45:30',
    status: 'Approved',
  },
  {
    user_id: 'CUST0003',
    user_name: 'Pinecone',
    last_login_date: '2023-09-03',
    last_login_time: '13:45:30',
    status: 'Pending',
  },
  {
    user_id: 'CUST0004',
    user_name: 'Ravi',
    last_login_date: '2023-09-04',
    last_login_time: '13:45:30',
    status: 'Approved',
  },
  {
    user_id: 'CUST0005',
    user_name: 'Elias',
    last_login_date: '2023-09-05',
    last_login_time: '13:45:30',
    status: 'Approved',
  },
  {
    user_id: 'CUST0006',
    user_name: 'Mariah Sandra',
    last_login_date: '2023-09-06',
    last_login_time: '13:45:30',
    status: 'Pending',
  },
  {
    user_id: 'CUST0007',
    user_name: 'Shi Ben Tan',
    last_login_date: '2023-09-01',
    last_login_time: '13:45:30',
    status: 'Approved',
  },
]

export const DEMO_BUSINESS_LIST_ADMIN = [
  {
    biz_id: 'BIZ0001',
    biz_name: 'SportsHaven Pro Shop',
    last_login_date: '2023-09-22',
    last_login_time: '13:45:30',
    city: 'Punggol',
    reg_date: '2021-10-01',
    status: 'Approved',
    phone_number: '+65 1234 5678',
    address: '123 Sports Street, Punggol',
    description: 'Your one-stop shop for all sporting goods and equipment in Punggol.',
  },
  {
    biz_id: 'BIZ0002',
    biz_name: 'ActiveGear Emporium',
    last_login_date: '2023-09-21',
    last_login_time: '14:30:15',
    city: 'Serangoon',
    reg_date: '2022-01-15',
    status: 'Pending',
    phone_number: '+65 9876 5432',
    address: '456 Sports Avenue, Serangoon',
    description: 'We provide a wide range of active wear and sports equipment for athletes of all levels.',
  },
  {
    biz_id: 'BIZ0003',
    biz_name: 'SportsFusion Outfitters',
    last_login_date: '2023-09-20',
    last_login_time: '12:15:45',
    city: 'Tampines',
    reg_date: '2020-12-05',
    status: 'Rejected',
    phone_number: '+65 8765 4321',
    address: '789 Sports Plaza, Tampines',
    description: 'Your source for the latest sports fashion and gear. Shop with us today!',
  },
  {
    biz_id: 'BIZ0004',
    biz_name: 'GameTime Sports World',
    last_login_date: '2023-09-19',
    last_login_time: '10:20:10',
    city: 'Woodlands',
    reg_date: '2022-03-10',
    status: 'Approved',
    phone_number: '+65 2345 6789',
    address: '101 Sports Road, Woodlands',
    description: 'We specialize in gaming and sports equipment for enthusiasts.',
  },
  {
    biz_id: 'BIZ0005',
    biz_name: 'EliteAthlete Sports Store',
    last_login_date: '2023-09-18',
    last_login_time: '11:55:22',
    city: 'Clementi',
    reg_date: '2021-11-20',
    status: 'Approved',
    phone_number: '+65 3456 7890',
    address: '222 Sports Lane, Clementi',
    description: 'Elevate your game with elite sports gear and accessories.',
  },
  {
    biz_id: 'BIZ0006',
    biz_name: 'AllStar Sporting Goods',
    last_login_date: '2023-09-17',
    last_login_time: '09:30:45',
    city: 'Jurong West',
    reg_date: '2020-09-22',
    status: 'Pending',
    phone_number: '+65 6789 0123',
    address: '333 Sports Court, Jurong West',
    description: 'Your destination for sports equipment and apparel from all-star brands.',
  },
  {
    biz_id: 'BIZ0007',
    biz_name: 'SportiveXpress Superstore',
    last_login_date: '2023-09-16',
    last_login_time: '16:40:05',
    city: 'Hougang',
    reg_date: '2021-07-12',
    status: 'Approved',
    phone_number: '+65 9876 1234',
    address: '444 Sports Mall, Hougang',
    description: 'Experience sports shopping like never before at SportiveXpress!',
  },
  {
    biz_id: 'BIZ0008',
    biz_name: 'PlayMaster Sports Essentials',
    last_login_date: '2023-09-15',
    last_login_time: '15:10:30',
    city: 'Bukit Timah',
    reg_date: '2020-08-28',
    status: 'Rejected',
    phone_number: '+65 8765 4321',
    address: '555 Sports Square, Bukit Timah',
    description: 'Your source for essential sports gear and accessories.',
  },
  {
    biz_id: 'BIZ0009',
    biz_name: 'FitnessFanatics Warehouse',
    last_login_date: '2023-09-14',
    last_login_time: '18:22:55',
    city: 'Ang Mo Kio',
    reg_date: '2021-05-19',
    status: 'Pending',
    phone_number: '+65 2345 6789',
    address: '666 Sports Complex, Ang Mo Kio',
    description: 'Discover a wide range of fitness equipment and accessories at our warehouse.',
  },
  {
    biz_id: 'BIZ0010',
    biz_name: 'SportSprint Sports Gear',
    last_login_date: '2023-09-13',
    last_login_time: '17:15:40',
    city: 'Sengkang',
    reg_date: '2022-02-14',
    status: 'Approved',
    phone_number: '+65 3456 7890',
    address: '777 Sports Boulevard, Sengkang',
    description: 'Sprint to success with high-quality sports gear from SportSprint.',
  },
];